# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Include tasks to validate variables
  ansible.builtin.include_tasks:
    file: validate-vars.yml
  tags: always

- name: Install and configure Load Balancer
  block:
    - name: Install load_balancer
      tags: install_load_balancer
      block:
        - name: Include common install tasks
          ansible.builtin.include_tasks:
            file: install-common.yml

        - name: Include online installation tasks
          ansible.builtin.include_tasks:
            file: install-online.yml
          when: not offline_install_enabled

        # - name: Include offline installation tasks
        #   ansible.builtin.include_tasks:
        #     file: install-offline.yml
        #   when: offline_install_enabled

    # - name: Configure Vault
    #   tags: configure_vault
    #   block:
    #     - name: Include configuration tasks
    #       ansible.builtin.include_tasks:
    #         file: configure-vault.yml

- name: Restart Vault if needed
  ansible.builtin.meta: flush_handlers
