# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Ensure cert directory exists
  ansible.builtin.file:
    path: "{{ self_signed_cert_dir }}"
    state: directory
    mode: '0755'

- name: Check if private key exists
  ansible.builtin.stat:
    path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_key }}"
  register: self_signed_cert_key_stat

- name: Check if certificate exists
  ansible.builtin.stat:
    path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_crt }}"
  register: self_signed_cert_cert_stat

- name: Check if certificate signing request exists
  ansible.builtin.stat:
    path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_csr }}"
  register: self_signed_cert_csr_stat

- name: Generate RSA private key
  community.crypto.openssl_privatekey:
    path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_key }}"
    size: "{{ self_signed_cert_key_size }}"
    type: RSA
    mode: '0600'
  when: not self_signed_cert_key_stat.stat.exists

- name: Generate a certificate signing request
  community.crypto.openssl_csr:
    path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_csr }}"
    privatekey_path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_key }}"
    common_name: platform
    subject_alt_name:
      - DNS:ip-10-0-0-22.ec2.internal
      - DNS:ip-10-0-0-26.ec2.internal
      - IP:34.224.29.163
      - IP:3.94.195.165
      - IP:10.0.0.26
      - IP:10.0.0.22
  when: not self_signed_cert_csr_stat.stat.exists


- name: Generate self-signed X.509 certificate
  community.crypto.x509_certificate:
    path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_crt }}"
    privatekey_path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_key }}"
    csr_path: "{{ self_signed_cert_dir }}/{{ self_signed_cert_csr }}"
    provider: selfsigned
    selfsigned_not_after: "+{{ self_signed_cert_days_valid }}d"
    mode: '0644'
  when: not self_signed_cert_cert_stat.stat.exists
