# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Validate and set installation variables
  tags: always
  block:
    - name: Validate component_name
      ansible.builtin.assert:
        that: component_name is defined
        fail_msg: "component_name must be defined"
      when: component_name is defined

    - name: Print Redis installation details when installing from source
      ansible.builtin.debug:
        msg: "Component ame: {{ component_name }}"
